version: '2'
services:
  postgres_db:
    image: postgres
  pocapi:
    build: .
    command: bash -c "mix ecto.create && mix ecto.migrate && ./_build/prod/rel/pocapi/bin/pocapi foreground"
    ports:
      - "4001:4001"
    depends_on:
      - postgres_db
